### PR TITLE
Add example of using an Riofile with kubernetes manifests

### PR DESCRIPTION
**Pull request by daxmc99**
Add an example using the kubernetes sample guestbook app to show how to
use a Riofile with additional k8s yaml. Also show how to add a
LetsEncrypt endpoint with Rio.

This example should be kept up to date via the tests that were integrated using this example

### CODE REVIEW

**Comment by daxmc99** [comment]
https://github.com/rancher/rio/issues/567

**Comment by StrongMonkey** [comment]
@daxmc99 lets wait for v0.6 so we can put this into riofile reference. This will be a really good example.

**Comment by StrongMonkey** [comment]
@daxmc99 Can you rebase this PR and put it into `riofile.md`?

**Comment by daxmc99** [comment]
@StrongMonkey Yeah, let me do that

**Pull request closed without merging**
